package kodra_guicustomcars;

import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
/**
 * @author besian kodra
 */
public class View extends javax.swing.JFrame 
{
    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
    }
    
    Model model;
    DecimalFormat df = new DecimalFormat("#.00");
    public void setModel(Model m)
    {
       model = m;
    }  
    public void displayOrder()
    {
        JOptionPane.showMessageDialog(rootPane, model.getName() + ", thank you for purchasing a " + model.getCarType() + " car from GUI Electric!"
                    + "\nThe total for this transaction including shipping and options is: " + "$" + df.format(model.getOrderTotal()));  
    }
    public JRadioButton getRdBtnShipment()
    {
        return rdbtnShipment;
    }
    public JRadioButton getRdBtnPickup()
    {
        return rdbtnPickup;
    }
    public JRadioButton getRdBtnSUV()
    {
        return rdbtnSUV;
    }
    public JRadioButton getRdBtnMidSized()
    {
        return rdbtnMidSized;
    }
    public JRadioButton getRdBtnCompact()
    {
        return rdbtnCompact;
    }
    public JTextField getTxtName()
    {
        return txtName;
    }
    public JCheckBox getChkBox4WD()
    {
        return chkbox4WD;
    }
    public JCheckBox getChkBoxCustomWheels()
    {
        return chkboxCustomWheels;
    }
    public JCheckBox getChkBoxEngravedLeather()
    {
        return chkboxEngravedLeather;
    }
    public JCheckBox getChkBoxSoundSystem()
    {
        return chkboxSoundSystem;
    }
    public JCheckBox getChkBoxSpoiler()
    {
        return chkboxSpoiler;
    }
    public JCheckBox getChkBoxSunRoof()
    {
        return chkboxSunRoof;
    }
    public void Reset()
    {
        rdbtnSUV.setSelected(false);
        rdbtnMidSized.setSelected(false);
        rdbtnCompact.setSelected(false);
        rdbtnShipment.setSelected(false);
        rdbtnPickup.setSelected(false);
        chkboxSunRoof.setSelected(false);
        chkboxSpoiler.setSelected(false);
        chkboxSoundSystem.setSelected(false);
        chkboxEngravedLeather.setSelected(false);
        chkboxCustomWheels.setSelected(false);
        chkbox4WD.setSelected(false);
        txtName.setText("Enter Name");
        txtAddress.setText("Enter Address");
        txtPhoneNumber.setText("Enter Phone Number");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdbtnPickup = new javax.swing.JRadioButton();
        rdbtnShipment = new javax.swing.JRadioButton();
        rdbtnCompact = new javax.swing.JRadioButton();
        rdbtnSUV = new javax.swing.JRadioButton();
        rdbtnMidSized = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chkbox4WD = new javax.swing.JCheckBox();
        chkboxSpoiler = new javax.swing.JCheckBox();
        chkboxEngravedLeather = new javax.swing.JCheckBox();
        chkboxCustomWheels = new javax.swing.JCheckBox();
        chkboxSunRoof = new javax.swing.JCheckBox();
        chkboxSoundSystem = new javax.swing.JCheckBox();
        javax.swing.JButton btnOrderNow = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Besian's Custom Cars App");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Mistral", 2, 36)); // NOI18N
        jLabel1.setText("New Vehicle Order Form");

        txtName.setText("Enter Your Name Here");
        txtName.setNextFocusableComponent(txtAddress);
        txtName.setRequestFocusEnabled(false);
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
        });
        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNameMouseClicked(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtAddress.setText("Enter Your Address Here");
        txtAddress.setNextFocusableComponent(txtPhoneNumber);
        txtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAddressFocusGained(evt);
            }
        });
        txtAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAddressMouseClicked(evt);
            }
        });

        txtPhoneNumber.setText("Enter Your Phone Number Here");
        txtPhoneNumber.setNextFocusableComponent(rdbtnPickup);
        txtPhoneNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPhoneNumberFocusGained(evt);
            }
        });
        txtPhoneNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPhoneNumberMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone:");

        rdbtnPickup.setBackground(new java.awt.Color(255, 255, 255));
        rdbtnPickup.setText("Pick Car Up (Free)");
        rdbtnPickup.setNextFocusableComponent(rdbtnShipment);
        rdbtnPickup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnPickupActionPerformed(evt);
            }
        });

        rdbtnShipment.setBackground(new java.awt.Color(255, 255, 255));
        rdbtnShipment.setText("Ship Car ($5000.00)");
        rdbtnShipment.setNextFocusableComponent(rdbtnCompact);
        rdbtnShipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnShipmentActionPerformed(evt);
            }
        });

        rdbtnCompact.setBackground(new java.awt.Color(255, 255, 255));
        rdbtnCompact.setText("Compact ($50,000.00)");
        rdbtnCompact.setNextFocusableComponent(rdbtnMidSized);
        rdbtnCompact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnCompactActionPerformed(evt);
            }
        });

        rdbtnSUV.setBackground(new java.awt.Color(255, 255, 255));
        rdbtnSUV.setText("Sport Utility Vehicle ($150,000.00)");
        rdbtnSUV.setNextFocusableComponent(chkbox4WD);
        rdbtnSUV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnSUVActionPerformed(evt);
            }
        });

        rdbtnMidSized.setBackground(new java.awt.Color(255, 255, 255));
        rdbtnMidSized.setText("Mid Size ($75,000.00)");
        rdbtnMidSized.setNextFocusableComponent(rdbtnSUV);
        rdbtnMidSized.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnMidSizedActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Mistral", 0, 18)); // NOI18N
        jLabel5.setText("Order Type");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Mistral", 0, 18)); // NOI18N
        jLabel6.setText("Body Type");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Mistral", 0, 18)); // NOI18N
        jLabel7.setText("Options");

        chkbox4WD.setBackground(new java.awt.Color(255, 255, 255));
        chkbox4WD.setText("Four Wheel Drive");
        chkbox4WD.setNextFocusableComponent(chkboxSpoiler);

        chkboxSpoiler.setBackground(new java.awt.Color(255, 255, 255));
        chkboxSpoiler.setText("Spoiler");
        chkboxSpoiler.setNextFocusableComponent(chkboxEngravedLeather);

        chkboxEngravedLeather.setBackground(new java.awt.Color(255, 255, 255));
        chkboxEngravedLeather.setText("Engraved Leather");
        chkboxEngravedLeather.setNextFocusableComponent(chkboxCustomWheels);

        chkboxCustomWheels.setBackground(new java.awt.Color(255, 255, 255));
        chkboxCustomWheels.setText("Custom Wheels");
        chkboxCustomWheels.setNextFocusableComponent(chkboxSunRoof);

        chkboxSunRoof.setBackground(new java.awt.Color(255, 255, 255));
        chkboxSunRoof.setText("Sun Roof");
        chkboxSunRoof.setNextFocusableComponent(chkboxSoundSystem);

        chkboxSoundSystem.setBackground(new java.awt.Color(255, 255, 255));
        chkboxSoundSystem.setText("Exclusive Sound System");
        chkboxSoundSystem.setNextFocusableComponent(btnOrderNow);

        btnOrderNow.setFont(new java.awt.Font("Mistral", 2, 36)); // NOI18N
        btnOrderNow.setForeground(new java.awt.Color(239, 0, 0));
        btnOrderNow.setText("Place Order");
        btnOrderNow.setNextFocusableComponent(txtName);
        btnOrderNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderNowActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kodra_guicustomcars/01.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kodra_guicustomcars/02.jpg"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Mistral", 2, 36)); // NOI18N
        jLabel10.setText("<html>GUI Electric Cars <p>Custom Automobiles</html>");

        jLabel11.setFont(new java.awt.Font("Mistral", 0, 18)); // NOI18N
        jLabel11.setText("Information");

        jLabel12.setFont(new java.awt.Font("Mistral", 0, 18)); // NOI18N
        jLabel12.setText("($10,000.00 each. The first one is free.)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbtnPickup)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAddress)
                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                                    .addComponent(txtName)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkbox4WD)
                                            .addComponent(chkboxCustomWheels))
                                        .addGap(186, 186, 186))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOrderNow)
                                    .addComponent(chkboxEngravedLeather)
                                    .addComponent(chkboxSoundSystem))
                                .addGap(27, 27, 27))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(rdbtnCompact)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbtnMidSized)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(rdbtnShipment))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(rdbtnSUV))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkboxSunRoof)
                                    .addComponent(chkboxSpoiler)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbtnPickup)
                            .addComponent(rdbtnShipment)))
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbtnCompact)
                            .addComponent(rdbtnSUV)
                            .addComponent(rdbtnMidSized))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkbox4WD)
                            .addComponent(chkboxSpoiler)
                            .addComponent(chkboxEngravedLeather))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkboxCustomWheels)
                            .addComponent(chkboxSoundSystem)
                            .addComponent(chkboxSunRoof))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOrderNow)
                                .addGap(21, 21, 21))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseClicked
        txtName.setText("");
    }//GEN-LAST:event_txtNameMouseClicked

    private void txtAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddressMouseClicked
        txtAddress.setText("");
    }//GEN-LAST:event_txtAddressMouseClicked

    private void txtPhoneNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPhoneNumberMouseClicked
        txtPhoneNumber.setText("");
    }//GEN-LAST:event_txtPhoneNumberMouseClicked

    private void rdbtnPickupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnPickupActionPerformed
        rdbtnShipment.setSelected(false);
        rdbtnPickup.setSelected(true);
    }//GEN-LAST:event_rdbtnPickupActionPerformed

    private void rdbtnShipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnShipmentActionPerformed
        rdbtnPickup.setSelected(false);
        rdbtnShipment.setSelected(true);
    }//GEN-LAST:event_rdbtnShipmentActionPerformed

    private void btnOrderNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderNowActionPerformed
        model.getOrder();    
        displayOrder();
        Reset();
    }//GEN-LAST:event_btnOrderNowActionPerformed

    private void rdbtnSUVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnSUVActionPerformed
        rdbtnSUV.setSelected(true);
        rdbtnMidSized.setSelected(false);
        rdbtnCompact.setSelected(false);
    }//GEN-LAST:event_rdbtnSUVActionPerformed

    private void rdbtnMidSizedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnMidSizedActionPerformed
        rdbtnSUV.setSelected(false);
        rdbtnMidSized.setSelected(true);
        rdbtnCompact.setSelected(false);
    }//GEN-LAST:event_rdbtnMidSizedActionPerformed

    private void rdbtnCompactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnCompactActionPerformed
        rdbtnSUV.setSelected(false);
        rdbtnMidSized.setSelected(false);
        rdbtnCompact.setSelected(true);
    }//GEN-LAST:event_rdbtnCompactActionPerformed

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        txtName.setText("");
    }//GEN-LAST:event_txtNameFocusGained

    private void txtAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusGained
        txtAddress.setText("");
    }//GEN-LAST:event_txtAddressFocusGained

    private void txtPhoneNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneNumberFocusGained
        txtPhoneNumber.setText("");
    }//GEN-LAST:event_txtPhoneNumberFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> 
        {
            new View().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkbox4WD;
    private javax.swing.JCheckBox chkboxCustomWheels;
    private javax.swing.JCheckBox chkboxEngravedLeather;
    private javax.swing.JCheckBox chkboxSoundSystem;
    private javax.swing.JCheckBox chkboxSpoiler;
    private javax.swing.JCheckBox chkboxSunRoof;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rdbtnCompact;
    private javax.swing.JRadioButton rdbtnMidSized;
    private javax.swing.JRadioButton rdbtnPickup;
    private javax.swing.JRadioButton rdbtnSUV;
    private javax.swing.JRadioButton rdbtnShipment;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}