package kodra_guitipper;

import java.awt.event.KeyEvent;
import java.text.DecimalFormat;

/**
 * @author besian kodra
 */
public class view extends javax.swing.JFrame 
{
    /**
     * Creates new form view
     */
    public view() 
    {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRestaurantName = new javax.swing.JTextField();
        txtBillTotal = new javax.swing.JTextField();
        txtTipPercentage = new javax.swing.JTextField();
        bttnCalculate = new javax.swing.JButton();
        bttnClose = new javax.swing.JButton();
        lblRestaurantName = new javax.swing.JLabel();
        lblTipAmount = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();
        lblErrors = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Besian's GUI Tipper");
        setResizable(false);

        jLabel1.setText("Restaurant Name");

        jLabel2.setText("Bill Total");

        jLabel3.setText("Tip Percentage");

        jLabel4.setText("<html>Welcome to Besian Kodra's Tip Calculator App made exclusively for Mr Jones' ITDEV 140 class. Please enter the restaurant name, bill total, and percentage you would like to tip in the boxes below and click Calculate in order to see the amount you should tip and a total which includes the tip amount. If you would like to close the app, please click the Close App button or use the X in the top right of the window. Have fun and enjoy your dining experience!</html>");

        txtBillTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBillTotalKeyTyped(evt);
            }
        });

        txtTipPercentage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTipPercentageKeyTyped(evt);
            }
        });

        bttnCalculate.setText("Calculate Tip");
        bttnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCalculateActionPerformed(evt);
            }
        });

        bttnClose.setText("Close App");
        bttnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCloseActionPerformed(evt);
            }
        });

        lblErrors.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bttnClose, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bttnCalculate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblGrandTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTipPercentage, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                            .addComponent(txtBillTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtRestaurantName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRestaurantName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTipAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRestaurantName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBillTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTipPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(lblRestaurantName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttnCalculate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTipAmount, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(lblGrandTotal)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnClose)
                    .addComponent(lblErrors))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_bttnCloseActionPerformed

    private void bttnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCalculateActionPerformed
        String restaurantName;
        restaurantName = txtRestaurantName.getText();
        
        double billTotal = 0;
        billTotal = Double.parseDouble(txtBillTotal.getText());
        
        double tipPercentage = 0;
        tipPercentage = Double.parseDouble(txtTipPercentage.getText());
        
        if(tipPercentage < 0.01)
        {
            lblErrors.setText("You have to enter a higher tip percentage.");
            lblRestaurantName.setText(null);
            lblTipAmount.setText(null);
            lblGrandTotal.setText(null);
        }
        else
        {
            lblErrors.setText(null);
            lblRestaurantName.setText("You are dining at: " + restaurantName);
            
            double tip = 0;
            tip = tipPercentage / 100;
            
            double tipAmount = 0;
            tipAmount = (tip * billTotal);
            
            DecimalFormat df = new DecimalFormat("#.00");
            
            lblTipAmount.setText("Your tip amount is: $" + df.format(tipAmount));
            
            double grandTotal = 0;
            grandTotal = tipAmount + billTotal;
            
            lblGrandTotal.setText("Your grand total is: $" + df.format(grandTotal));
        }
    }//GEN-LAST:event_bttnCalculateActionPerformed

    private void txtBillTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBillTotalKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_PERIOD) ||c==KeyEvent.VK_DELETE))
                {
                    getToolkit().beep();
                    evt.consume();
                }
    }//GEN-LAST:event_txtBillTotalKeyTyped

    private void txtTipPercentageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipPercentageKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_PERIOD) || c==KeyEvent.VK_DELETE))
                {
                    getToolkit().beep();
                    evt.consume();
                }
    }//GEN-LAST:event_txtTipPercentageKeyTyped
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new view().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCalculate;
    private javax.swing.JButton bttnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblErrors;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblRestaurantName;
    private javax.swing.JLabel lblTipAmount;
    private javax.swing.JTextField txtBillTotal;
    private javax.swing.JTextField txtRestaurantName;
    private javax.swing.JTextField txtTipPercentage;
    // End of variables declaration//GEN-END:variables
}